name: Docker for gharc-texlive-arm
on:
  push:
    branches: [ master ]
    paths:
      - 'gharc-texlive-arm/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'gharc-texlive-arm/**'
  workflow_dispatch:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker Build
        shell: bash
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --platform linux/arm64 gharc-texlive-arm/ -t ghcr.io/dkoch84/gharc-texlive-arm:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
          docker images
      - name: Docker Push
        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u dkoch84 --password-stdin
          docker push ghcr.io/dkoch84/gharc-texlive-arm:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)